# ---
# - hosts: node_exporter
#   become: yes
#   become_method: sudo
#   roles:
#     - prometheus_node_exporter

# - hosts: consul_exporter
#   become: yes
#   become_method: sudo
#   roles:
#     - prometheus_consul_exporter

# - hosts: consul_agent
#   become: yes
#   become_method: sudo
#   roles:
#     - consul_install

# - name: Configure the consul
#   hosts: consul_agent
#   become: yes
#   become_method: sudo
#   roles:
#     - consul_configure

# - hosts: grafana
#   become: yes
#   become_method: sudo
#   roles:
#     - grafana

# - hosts: prometheus
#   become: yes
#   become_method: sudo
#   roles:
#     - prometheus

- hosts: filebeat
  become: yes
  become_method: sudo
  roles:
    - filebeat_install