---
- name: Create Nginx Repo
  yum_repository:
    name: Nginx
    description: EPEL Nginx repo
    baseurl: https://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: no
    enabled: yes

- name: nginx | Install nginx
  yum:
    name:
      - libselinux-python
      - nginx
    state: present

- name: nginx | Configure nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: nginx | start nginx
  service:
    name: nginx
    enabled: yes
    state: started

