---

- name: Test distribution
  assert:
    that: >
      ansible_facts.os_family == "RedHat" or
      ansible_facts.os_family == "Debian"

- name: Configure Filebeat
  template:
    src: filebeat.yml.j2
    dest: "{{ filebeat_config_file }}"
  notify:
    - Restart Filebeat service
  tags:
    - filebeat_config
