---

galaxy_info:
  author: Jiri Tyr
  description: A role that installs Elastic Filebeat.
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - xenial
  galaxy_tags:
    - monitoring
    - logging
dependencies:
  - config_encoder_filters
