---
# handlers file for alerta2
- name: Reload the daemon
  command: "systemctl daemon-reload"
  listen: "daemon_reload"

- name: RStart the uwsgi
  service:
    name: "uwsgi"
    state: restarted
  listen: restart_uwsgi

- name: RStart the nginx
  service:
    name: "nginx"
    state: rstarted
  listen: restart_nginx