
- name: Register the node_exporter with consul
  template:
    src: external.json.j2
    dest: "{{ consul_config_dir }}/external.hcl"
    owner: "{{ consul_username }}"
    group: "{{ consul_groupname }}"
    mode: 0750
  notify: restart_service